/* Bakes the web fonts into the product as data: URIs.
 *
 * The whole promise is that one file opens anywhere and works — a laptop in a
 * lecture theatre, no network, not yours. A <link> to a font CDN quietly
 * breaks exactly that: the layout survives, but every face falls back and the
 * thing you rehearsed against is not the thing on the screen.
 *
 * Only the basic-latin subset is kept. CJK is never embedded: no web font
 * would be a sane size, and the system faces (PingFang, Noto, Microsoft
 * YaHei) are what the token stacks name anyway.
 *
 * Needs network; run it when the font set changes, and commit the result.
 * Run: node tools/embed_fonts.mjs
 */
import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';

const OUT = path.resolve(import.meta.dirname, '..', 'viewer', 'css', '00-fonts.css');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';   /* asks for woff2 */
/* Only the faces the product actually paints. Newsreader is asked for as
   discrete instances rather than as a variable range: the two variable files
   are 271 KB of the 492 KB, and nothing here interpolates a weight. */
const URL = 'https://fonts.googleapis.com/css2'
  + '?family=IBM+Plex+Mono:wght@400;500;600'
  + '&family=IBM+Plex+Sans+Condensed:wght@600'
  + '&family=IBM+Plex+Sans:wght@400;500;600'
  + '&family=Instrument+Serif'
  + '&family=Newsreader:ital,wght@0,400;0,600;1,400;1,600'
  + '&display=swap';

const get = (url, binary) =>
  execFileSync('curl', ['-sSfL', '-A', UA, url], { maxBuffer: 64 << 20, encoding: binary ? 'buffer' : 'utf8' });

const css = get(URL);
const blocks = css.match(/\/\*[^*]*\*\/\s*@font-face\s*\{[^}]*\}/g) || css.match(/@font-face\s*\{[^}]*\}/g) || [];

let kept = 0, dropped = 0, bytes = 0;
const out = [];
for (const block of blocks) {
  /* Google labels each subset in a comment and pins it with unicode-range;
     U+0000-00FF is the basic-latin block, which is all this product sets in
     a web font. */
  if (!/U\+0000-00FF/.test(block)) { dropped++; continue; }
  const m = /url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/.exec(block);
  if (!m) { dropped++; continue; }
  const buf = get(m[1], true);
  bytes += buf.length;
  kept++;
  out.push(block
    .replace(/\/\*[^*]*\*\/\s*/, '')
    .replace(m[0], `url(data:font/woff2;base64,${buf.toString('base64')})`));
}

fs.writeFileSync(OUT, `/* Generated by tools/embed_fonts.mjs — do not edit by hand.

   The faces the product needs, inlined, so the one file works with no
   network. Basic latin only; CJK falls to the system faces the token stacks
   name, because no CJK web font is a sane size for a file you email around.

   ${kept} faces · ${(bytes / 1024).toFixed(0)} KB of woff2 before base64. */
${out.join('\n')}
`);
console.log(`kept ${kept} latin faces (${(bytes / 1024).toFixed(0)} KB woff2), dropped ${dropped} other subsets`);
console.log(`wrote ${OUT} — ${(fs.statSync(OUT).size / 1024).toFixed(0)} KB`);
